Goya/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('items/', include(('items.urls', 'items'), namespace='items')),
    path('inventoryLoads/', include(('inventoryLoads.urls',
         'inventoryLoads'), namespace='inventoryLoads')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from dashboard import views

urlpatterns = [
    path(
        route='',
        view=views.welcome,
        name = 'welcome'
    ),
]

inventoryLoads/urls.py
from django.urls import path
from inventoryLoads import views


urlpatterns = [
    path(
        route='provider/',
        view=views.provider_feed,
        name='inventory_provider'
    ),
    path(
        route='provider/new',
        view=views.provider_new,
        name='inventory_provider_new'
    ),
    # path(
    #   route='provider/newc',
    #   view=views.ProviderNew.as_view(),
    #   name='inventory_provider_newc'
    # ),
    path(
        route='provider/edit/<int:pk>',
        view=views.provider_edit,
        name='inventory_provider_edit'
    ),
    # path(
    #    route='provider/delete/<int:pk>',
    #    view=views.ProviderDelete.as_view(),
    #    name='inventory_provider_delete'
    # ),
    path(
        route='provider/delete/<int:pk>',
        view=views.provider_delete,
        name='inventory_provider_delete'
    ),
    path(
        route='',
        view=views.inventoryload_feed,
        name='inventory_load_feed'
    ),
    path(
        route='<int:pk>',
        view=views.inventoryLoad_detail,
        name='inventory_load_detail'
    ),
    path(
        route='new',
        view=views.InventoryCreateview.as_view(),
        name='inventory_new'
    )
]

items/urls.py
from django.urls import path
from items import views

urlpatterns = [
    path(
        route='',
        view=views.ItemsListView.as_view(),
        name='items_feed'
    ),
    path(
        route='dashboard',
        view=views.items_dashboard,
        name='items_dashboard'
    ),
    path(
        route='new',
        view=views.item_new,
        name='item_new'
    ),
    path(
        route='item/<int:pk>',
        view=views.ItemEdit.as_view(),
        name='items_update'
    ),
    path(
        route='item/delete/<int:pk>',
        view=views.items_delete,
        name='items_delete'
    ),
    path(
        route='categories/',
        view=views.categories_feed,
        name='categories_feed'
    ),
    path(
        route='categories/<int:pk>',
        view=views.CategoryEdit.as_view(),
        name='categories_edit'
    ),
    path(
        route='categories/new',
        view=views.CategoryCreate.as_view(),
        name='categories_new'
    ),
    path(
        route='categories/delete/<int:pk>',
        view=views.categories_delete,
        name='categories_delete'
    ),
]

dashboard/models.py
from django.db import models

# Create your models here.

inventoryLoads/models.py
from django.db import models
from items.models import Item
from django.contrib.auth.models import User

# Create your models here.


class Provider(models.Model):
    name = models.CharField(max_length=45)
    address = models.CharField(max_length=300, null=True)
    email = models.EmailField(null=True)
    phone = models.CharField(max_length=45, null= True)
    site = models.URLField(null=True)
    contact_name = models.CharField(max_length=150, null=True)
    contac_email = models.EmailField(null=True)
    contact_phone = models.PositiveIntegerField(null=True)
    last_user_update = models.CharField(max_length=45,null=True)
    last_date_update = models.DateField(auto_now = True, null=True)
    def __str__(self):
        return self.name


class InventoryLoad(models.Model):
    date = models.DateTimeField(auto_now_add=True, blank=False, null=False)
    description = models.TextField(max_length=500)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    document_type = models.CharField(max_length=50, null=False, blank=False, default='N/A')
    document_number = models.CharField(max_length=200, null=False, blank=False, default='N/A')
    provider = models.ForeignKey(Provider, null = False, on_delete=models.PROTECT)
    last_user_update = models.ForeignKey(User, on_delete = models.PROTECT)
    last_date_update = models.DateField(auto_now = True)


    def __str__(self):
        return '{} number {} date {}'.format(self.document_type,self.document_number,self.date)



class InventoryLoadDetail(models.Model):
    item = models.ForeignKey(Item, null=False, on_delete=models.PROTECT)
    quantity = models.PositiveSmallIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    inventoryLoad = models.ForeignKey(InventoryLoad, null = False, on_delete= models.PROTECT)
    last_user_update = models.ForeignKey(User, on_delete = models.PROTECT)
    last_date_update = models.DateField(auto_now = True)

    def __str__(self):
        return '{} {} {}'.format(self.inventoryLoad.document_type, self.inventoryLoad.document_number, self.item.name)

inventoryLoads/forms.py
from django import forms
from inventoryLoads.models import *
from django.forms.models import inlineformset_factory


ChildFormset = inlineformset_factory(
    InventoryLoad, InventoryLoadDetail, fields=('item', 'quantity', 'price')
)


class ProviderForm(forms.ModelForm):
    class Meta:
        model = Provider
        fields='__all__'


class InventoriLoadForm(forms.ModelForm):
    class Meta: 
        model = InventoryLoad
        fields = '__all__'


class InventoryLoadDetailForm(forms.ModelForm):
    class Meta:
        model = InventoryLoadDetail
        fields = '__all__'

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required
def welcome(request):

    context = {}

    return render(request, 'welcome.html', context)

inventoryLoads/views.py
from django.shortcuts import render, redirect
from inventoryLoads.models import Provider, InventoryLoad
from inventoryLoads.forms import *
from django.shortcuts import render
from django.core.paginator import Paginator
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy


# Create your views here.


def provider_feed(request):
    providers = Provider.objects.all()
    paginator = Paginator(providers, 20)

    page_number = request.GET.get('page')
    page_object = paginator.get_page(page_number)
    context = {
        'providers': providers,
        'page_object': page_object
    }
    return render(request, 'inventoryLoads/provider_feed.html', context)


# class ProviderNew(LoginRequiredMixin, CreateView):
 #   template_name = 'inventoryLoads/provider_form.html'
  #  model = Provider
   # fields = '__all__'
    # success_url = reverse_lazy('inventoryLoads:inventory_provider')

@login_required
def provider_new(request):
    form = ProviderForm()
    if request.method == 'POST':
        form = ProviderForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('inventoryLoads:inventory_provider')
    context = {
        'form': form,
    }
    return render(request, 'inventoryLoads/provider_new.html', context)


@login_required
def provider_edit(request, pk):
    provider = Provider.objects.get(id=pk)
    form = ProviderForm(instance=provider)
    if request.method == 'POST':
        form = ProviderForm(request.POST, instance=provider)
        if form.is_valid():
            form.save()
            return redirect('inventoryLoads:inventory_provider')
    context = {
        'form': form
    }
    return render(request, 'inventoryLoads/provider_edit.html', context)


@login_required
def provider_delete(request, pk):
    provider = Provider.objects.get(id=pk)
    provider.delete()
    context = {
        'provider': provider
    }
    return redirect('inventoryLoads:inventory_provider')


# class ProviderDelete(LoginRequiredMixin, DeleteView):
#    model = Provider
#    fields = '__all__'
#    template_name = 'inventoryLoads/provider_delete.html'
#    success_url = reverse_lazy('inventoryLoads:provider_feed')


def inventoryload_feed(request):
    inventory = InventoryLoad.objects.all()
    paginator = Paginator(inventory, 20)

    page_number = request.GET.get('page')
    page_object = paginator.get_page(page_number)
    context = {
        'providers': inventory,
        'page_object': page_object
    }
    return render(request, 'inventoryLoads/inventory_feed.html', context)


def inventoryLoad_detail(request, pk):
    Inventoryload = InventoryLoad.objects.get(id=pk)
    detail_list = Inventoryload.inventoryloaddetail_set.all()

    paginator = Paginator(detail_list, 20)

    page_number = request.GET.get('page')
    page_object = paginator.get_page(page_number)
    context = {
        'inventoryload': Inventoryload,
        'page_object': page_object
    }
    return render(request, 'inventoryLoads/inventory_description.html', context)


def inventoryLoad_new(request):
    form = InventoriLoadForm()
    if request.method == 'POST':
        form = InventoriLoadForm(request.POST)
        if form.is_valid():
            form.save()
            redirect('inventoryLoads:inventory_load_feed')
    context = {
        'form': form

    }
    return render(request, 'inventoryLoads/inventoryload_form.html', context)


class InventoryCreateview(CreateView):
    model = InventoryLoad
    fields = '__all__'

    def get_context_data(self, **kwargs):
        # we need to overwrite get_context_data
        # to make sure that our formset is rendered
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data["children"] = ChildFormset(self.request.POST)
        else:
            data["children"] = ChildFormset()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        children = context["children"]
        self.object = form.save()
        if children.is_valid():
            children.instance = self.object
            children.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("parents:list")

templates/inventoryLoads/dashboard.html
{% extends 'main.html' %}
{% block content %}


<div class="row">

    <div class="col-lg-3 col-6">
        <!-- small card -->
        <div class="small-box bg-warning">
            <div class="inner">
                <h3>{{ total_ingresos }}</h3>
                <p>User Registrations</p>
            </div>
            <div class="icon">
                <i class="fas fa-user-plus"></i>
            </div>
            <a href="#" class="small-box-footer">
                More info <i class="fas fa-arrow-circle-right"></i>
            </a>
        </div>
    </div>

    <div class="col-lg-3 col-6">
        <!-- small card -->
        <div class="small-box bg-warning">
            <div class="inner">
                <h3>44</h3>
                <p> Proveedores </p>
            </div>
            <div class="icon">
                <i class="fas fa-user-plus"></i>
            </div>
            <a href="#" class="small-box-footer">
                More info <i class="fas fa-arrow-circle-right"></i>
            </a>
        </div>
    </div>
</div>


<div class = "container">
 <div class="row">
    <div class="col-md-12">
        <div class="card-header">
            <h3 class="card-title">Ingreso de productos a Inventario</h3>

                <div class="card-tools">
                  <div class="input-group input-group-sm" style="width: 150px;">
                    <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                    <div class="input-group-append">
                      <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                    </div>
                  </div>
                </div>
              </div>
    </div>

 </div>


</div>

    <div class="col-md-12">


        <div class="card card-body">
            <a class="btn btn-primary btn-sm btn-block" href="">Create a Customer</a>
            <table class="table table-sm">
                <tr>
                    <th></th>
                    <th>NAME</th>
                    <th>STOCK</th>
                    <th>CATEGORY</th>
                    <th>OPTIONS</th>

                </tr>
               {% for article in object_list %}
                <tr>
                    <td><a href="">View</a></a></td0>
                    <td>{{article.name}}</td>
                    <td>{{article.stock}}</td>
                    <td>{{article.category}}</td>
                    <td>update and remove</td>
                </tr>
                {% endfor %}

            </table>
        </div>
    </div>
    

    


</div>
{% endblock %}

templates/inventoryLoads/inventory_description.html
{% extends 'main.html' %}
{% block content_head %}

<h1 class="m-0 text-dark">Dashboard</h1>
{% endblock %}
{% block content_main %}

<div class="col-10 form-item">
  <div class="card card-secondary">
    <div class="card-header">
      <h3 class="card-title-add">Available Providers </h3>
      <a class = "btn btn-danger text-align-left" href = "{% url 'items:items_feed'%}"> Back</a>


      <div class="card-tools">
        <div class="input-group input-group-sm" style="width: 150px;">
          <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

          <div class="input-group-append">
            <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
          </div>
        </div>
      </div>
    </div>

    <div class="invoice p-3 mb-3">
      <!-- title row -->
      <div class="row">
        <div class="col-12">
          <h4>
            <i class="fas fa-globe"></i> BCS-Meda, Inc.
            <small class="float-right">Date: {{ inventoryload.date}}</small>
          </h4>
        </div>
        <!-- /.col -->
      </div>
      <!-- info row -->
      <div class="row invoice-info">
        <div class="col-sm-4 invoice-col">
          Provider
          <address>
            <strong>{{ inventoryload.provider.name }}</strong><br>
            {{ inventoryload.provider.address }}<br>
            Phone: {{ inventoryload.provider.phone }}<br>
            Email: {{ inventoryload.provider.email }}
          </address>
        </div>
        <!-- /.col -->
      
        <!-- /.col -->
        <div class="col-sm-4 invoice-col">
          <b>{{ inventoryload.document_type}} #{{ inventoryload.document_number }}</b><br>
          <br>
          <b>Order ID:</b> 4F3S8J<br>
          <b>Payment Due:</b> 2/22/2014<br>
          <b>Account:</b> 968-34567
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

      <!-- Table row -->
      <div class="row">
        <div class="col-12 table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Qty</th>
                <th>Product</th>
                <th>Serial #</th>
                <th>Description</th>
                <th>Subtotal</th>
              </tr>
            </thead>
            <tbody>
            {% for product in page_object %}
              <tr>
                <td>{{ product.quantity }}</td>
                <td>{{ product.item.name }}</td>
                <td>######</td>
                <td>{{ product.item.description }}</td>
                <td>{{ product.price }}</td>
              </tr>
            
            {% endfor %}
     
            </tbody>
          </table>
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

      <div class="row">
        <!-- accepted payments column -->
        <div class="col-6">
          <p class="lead">Payment Methods:</p>
          <img src="../../dist/img/credit/visa.png" alt="Visa">
          <img src="../../dist/img/credit/mastercard.png" alt="Mastercard">
          <img src="../../dist/img/credit/american-express.png" alt="American Express">
          <img src="../../dist/img/credit/paypal2.png" alt="Paypal">

          <p class="text-muted well well-sm shadow-none" style="margin-top: 10px;">
            Etsy doostang zoodles disqus groupon greplin oooj voxy zoodles, weebly ning heekya handango imeem
            plugg
            dopplr jibjab, movity jajah plickers sifteo edmodo ifttt zimbra.
          </p>
        </div>
        <!-- /.col -->
        <div class="col-6">
          <p class="lead">Amount Due 2/22/2014</p>

          <div class="table-responsive">
            <table class="table">
              <tbody>
                <tr>
                  <th style="width:50%">Subtotal:</th>
                  <td>$250.30</td>
                </tr>
                <tr>
                  <th>Tax (9.3%)</th>
                  <td>$10.34</td>
                </tr>
                <tr>
                  <th>Shipping:</th>
                  <td>$5.80</td>
                </tr>
                <tr>
                  <th>Total:</th>
                  <td>{{ inventoryload.total }}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

      <!-- this row will not appear when printing -->
      <div class="row no-print">
        <div class="col-12">
          <a href="invoice-print.html" target="_blank" class="btn btn-default"><i class="fas fa-print"></i> Print</a>
          <button type="button" class="btn btn-success float-right"><i class="far fa-credit-card"></i> Submit
            Payment
          </button>
          <button type="button" class="btn btn-primary float-right" style="margin-right: 5px;">
            <i class="fas fa-download"></i> Generate PDF
          </button>
        </div>
      </div>
    </div>
  </div>
  <!-- /.card-body -->
</div>
<!-- /.card -->
</div>



{% endblock %}

templates/inventoryLoads/inventory_feed.html
{% extends 'main.html' %}
{% block content_head %}

<h1 class="m-0 text-dark">Dashboard</h1>
{% endblock %}
{% block content_main %}

<div class="col-10 form-item"">
  <div class="card card-secondary">
    <div class="card-header">
      <h3 class="card-title-add">Available Providers </h3>
      <a class = "btn btn-danger text-align-left" href = "{% url 'items:items_feed'%}"> Back</a>


      <div class="card-tools">
        <div class="input-group input-group-sm" style="width: 150px;">
          <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

          <div class="input-group-append">
            <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
          </div>
        </div>
      </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body table-responsive p-0">
      <table class="table table-hover text-nowrap">
        <thead>
          <tr>
            <th>Date</th>
            <th>Description</th>
            <th>Total</th>
            <th>Docment</th>
            <th>Provider</th>
          </tr>
        </thead>
        <tbody>
          {% for load in page_object %}
          <tr>
            <td>{{ load.date }}</td>
            <td>{{ load.description }}</td>
            <td>{{ load.total }}</td>
            <td>{{ load.document_type }} {{ load.document_number }}</td>
            <td>{{ load.provider.name }}</td>
            <td>
              <div class="btn-group">
                <a href="#" class="btn btn-info">Edit</a>
                <a href="#" class="btn btn-danger">Delete</a>
              </div>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

      {% include 'paginator.html'%}

      </div>

    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
</div>



{% endblock %}

templates/inventoryLoads/inventoryload_form.html
{% extends 'main.html' %}
{% block content_head %}

<h1 class="m-0 text-dark">Dashboard</h1>
{% endblock %}
{% block content_main %}

<div class="col-10 form-item">
  <div class="card card-secondary">
    <div class="card-header">
      <h3 class="card-title-add">Available Providers </h3>

      <div class="card-tools">
        <div class="input-group input-group-sm" style="width: 150px;">
          <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

          <div class="input-group-append">
            <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
          </div>
        </div>
      </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body table-responsive p-0">
     <form method = "post">
     {% csrf_token %}
     {{form.as_p}}
     <br>
     {{ children }}<br>
     </form>

      {% include 'paginator.html'%}

      </div>

    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
</div>



{% endblock %}

templates/inventoryLoads/provider_delete.html
{% extends 'main.html' %}


<!-- <h1 class="m-0 text-dark">Dashboard</h1> -->block %}
{% block content_main %}
{%include 'searchbar.html'%}

<br>

<div class="col-12 pl-5 pr-5">
    <div class="card-body på-0">
        <form action='.' method='POST'>{% csrf_token %}
            <h1>Do you want to delete the provider </h1>
            <p><input type='submit' value='Yes' />
                <a href='../'>Cancel</a>
            </p>

        </form>
    </div>
</div>


{% endblock %}

templates/inventoryLoads/provider_feed.html
{% extends 'main.html' %}


<!-- <h1 class="m-0 text-dark">Dashboard</h1> -->block %}
{% block content_main %}
{%include 'searchbar.html'%}

<!-- <div class = "col-md-1 pl-5" style="align-items: flex-end;">
        <a  href="{% url 'items:item_new' %}" class = "btn-add-item " id="rotation"> </a>
    </div> -->
<br>

<div class="col-12 pl-5 pr-5">
  <div class="card">
    <div class="card-header bk-tab">
      <h3 class="card-title text-goya ">PROVIDERS</h3>

      <div class="col-md-1 pl-5" style="align-items: flex-end;">
        <a href="{% url 'inventoryLoads:inventory_provider_new' %}" class="btn-add-item " id="rotation"> </a>
      </div>
      <div class="card-tools">

      </div>
    </div>
  </div>

  <!-- /.card-header -->
  <div class="card-body table-responsive p-0">
    <table class="table table-hover text-nowrap">
      <thead class="head-td">
        <tr>

          <th>Name</th>
          <th>address</th>
          <th>email</th>
          <th>phone</th>
          <th>site</th>

        </tr>
      </thead>
      <tbody>
        {% for provider in providers %}

        <td>{{ provider.name }}</td>
        <td>{{ provider.address }}</td>
        <td>{{ provider.email }}</td>
        <td>{{ provider.phone }}</td>
        <td>{{ provider.site }}</td>

        <td>
          <div class="btn-group">
            <a href="{% url 'inventoryLoads:inventory_provider_edit' provider.id %}" class="btn btn-info">Edit</a>
            <a href="{% url 'inventoryLoads:inventory_provider_delete' provider.id %}" class="btn btn-danger">Delete</a>
          </div>
        </td>
        </tr>
        {% endfor %}

      </tbody>

    </table>
  </div>
  <!-- /.card-body -->
</div>
<!-- /.card -->
</div>
<div style="margin-top: 20px; height: 150px;" class="pl-5">
  <div class="pagination pl-5">


  </div>
  {% include 'paginator.html' %}
</div>




{% endblock %}

templates/inventoryLoads/provider_form.html
{% extends 'main.html' %}
{% block content_head %}

<h1 class="m-0 text-dark">Provider Form</h1>

{% endblock %}
{% block content_main %}

<div class="col-10 form-item">
  <div class="card card-secondary">
    <div class="card-header ">
      <h3 class="card-title-add ">PROVIDER FORM</h3>
      <a class = "btn btn-danger text-align-left" href = "{% url 'items:items_feed'%}"> Back</a>

      <!-- <div class="card-tools">
        <div class="input-group input-group-sm" style="width: 150px;">
          <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

          <div class="input-group-append">
            <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
          </div>
        </div>
      </div> -->
    </div>
    <!-- /.card-header -->
    <div class="card-body på-0">
      <form action="" method="POST" enctype="multipart/form-data" >
        {% csrf_token %}
        <div class="col-sm-6 form-item">
          <!-- text input -->
          <div class="form-group" style="font-family: goya-font;">
            <label>Name</label>
            <input type="text" class="form-control" placeholder="Enter the provider name ..." name="name" id="name" max-length= "45">
            {% for error in form.name.errors %}
            {{ error }}
            {% endfor %}
          </div>
        </div>
        <div class="col-sm-6 form-item">
          <!-- text input -->
          <div class="form-group" style="font-family: goya-font;">
            <label> Address </label>
            <input type="text" class="form-control" placeholder="enter the address of the company" name="address" id="address" max-length = "300">
            {% for error in form.address.errors %}
            {{ error }}
            {% endfor %}

          </div>
        </div>

        <div class="col-sm-6 form-item">
          <!-- text input -->
          <div class="form-group" style="font-family: goya-font;">
            <label>Email</label>
            <input type="email" class="form-control" placeholder="Enter the email address" name="email" id="email" max-length="150">
            {% for error in form.email.errors %}
            {{ error }}
            {% endfor %}

          </div>
        </div>
        <div class="col-sm-6 form-item">
          <!-- text input -->
          <div class="form-group" style="font-family: goya-font;">
            <label>phone</label>
            <input type="text" class="form-control" placeholder="Enter the phone number" name="phone" id="phone" max-length="25">


            {% for error in form.phone.errors %}
            {{ error }}
            {% endfor %}

          </div>
        </div>
        <div class="col-sm-6 form-item">
          <!-- text input -->
          <div class="form-group" style="font-family: goya-font;">
            <label>site</label>
            <input type="text" class="form-control" placeholder="Type the web site ..." name="site" id="site">

            {% for error in form.site.errors %}
            {{ error }}
            {% endfor %}

          </div>
        </div>
        <div class="col-sm-6 form-item">
          <!-- text input -->
          <div class="form-group" style="font-family: goya-font;">
            <label>Contact Name</label>
            <input type="text" class="form-control" placeholder="Enter the contact name..." name="contact_name" id="contact_name" max-length="90">

            {% for error in form.contact_name.errors %}
            {{ error }}
            {% endfor %}

          </div>
        </div>
        <div class="col-sm-6 form-item">
          <!-- text input -->
          <div class="form-group" style="font-family: goya-font;">
            <label>Contact email</label>
            <input type="text" class="form-control" placeholder="Enter the contact direct phone..." name="contac_email"
              id="contact-email" max-length="45" >
            {% for error in form.contac_email.errors %}
            {{ error }}
            {% endfor %}

          </div>
        </div>
         <div class="col-sm-6 form-item">
          <!-- text input -->
          <div class="form-group" style="font-family: goya-font;">
            <label>Contact phone</label>
            <input type="text" class="form-control" placeholder="Enter the contact direct phone..." name="contact_phone"
              id="contact_phone" max-length="45" >
            {% for error in form.contact_phone.errors %}
            {{ error }}
            {% endfor %}

          </div>
        </div>

        <button class="btn btn-primary-item btn-block mt-5" type="submit">Register!</button>
      </form>

    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
</div>



{% endblock %}