Goya/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('items/', include(('items.urls', 'items'), namespace='items')),
    path('inventoryLoads/', include(('inventoryLoads.urls',
         'inventoryLoads'), namespace='inventoryLoads')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventoryLoads/urls.py
from django.urls import path
from inventoryLoads import views


urlpatterns = [
    path(
        route='provider/',
        view=views.provider_feed,
        name='inventory_provider'
    ),
    path(
        route='provider/new',
        view=views.provider_new,
        name='inventory_provider_new'
    ),
    # path(
    #   route='provider/newc',
    #   view=views.ProviderNew.as_view(),
    #   name='inventory_provider_newc'
    # ),
    path(
        route='provider/edit/<int:pk>',
        view=views.provider_edit,
        name='inventory_provider_edit'
    ),
    # path(
    #    route='provider/delete/<int:pk>',
    #    view=views.ProviderDelete.as_view(),
    #    name='inventory_provider_delete'
    # ),
    path(
        route='provider/delete/<int:pk>',
        view=views.provider_delete,
        name='inventory_provider_delete'
    ),
    path(
        route='',
        view=views.inventoryload_feed,
        name='inventory_load_feed'
    ),
    path(
        route='<int:pk>',
        view=views.inventoryLoad_detail,
        name='inventory_load_detail'
    ),
    path(
        route='new',
        view=views.InventoryCreateview.as_view(),
        name='inventory_new'
    )
]

items/urls.py
from django.urls import path
from items import views

urlpatterns = [
    path(
        route='',
        view=views.ItemsListView.as_view(),
        name='items_feed'
    ),
    path(
        route='dashboard',
        view=views.items_dashboard,
        name='items_dashboard'
    ),
    path(
        route='new',
        view=views.item_new,
        name='item_new'
    ),
    path(
        route='item/<int:pk>',
        view=views.ItemEdit.as_view(),
        name='items_update'
    ),
    path(
        route='item/delete/<int:pk>',
        view=views.items_delete,
        name='items_delete'
    ),
    path(
        route='categories/',
        view=views.categories_feed,
        name='categories_feed'
    ),
    path(
        route='categories/<int:pk>',
        view=views.CategoryEdit.as_view(),
        name='categories_edit'
    ),
    path(
        route='categories/new',
        view=views.CategoryCreate.as_view(),
        name='categories_new'
    ),
    path(
        route='categories/delete/<int:pk>',
        view=views.categories_delete,
        name='categories_delete'
    ),
]

users/urls.py
from django.urls import path
from users import views

urlpatterns = [

    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'),
    path(
        route='logout/',
        view=views.LoginView.as_view(),
        name='logout'),
    path(
        route='singup/',
        view=views.SignupView.as_view(),
        name='signup'),
    path(
        route='me/profile/',
        view=views.UpdateProfileView.as_view(),
        name='update'),

    path(
        route='<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

]

templates/aside.html
{% load static %}
<aside class="main-sidebar elevation-4 sidebar-light-navy">
  <!-- Brand Logo -->
  <a href="#" class="brand-link navbar-warning">
    <img src="{% static '/img-dash/logo-goya.svg' %}" alt="Goya">
  </a>

  <!-- Sidebar -->
  <div class="sidebar" style="height: 79vh;">
    <!-- Sidebar user panel (optional) -->

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column nav-legacy" data-widget="treeview" role="menu"
        data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
        <li class="nav-item has-treeview">
          <a href="/" class="nav-link active">
            <i class="nav-icon fas fa-chart-bar"></i>
            <p>
              Dashboard
              <i class="fas fa-shopping-basket right"></i>
            </p>
          </a>
        </li>
        <li class="nav-item has-treeview menu-open">
          <a href="" class="nav-link ">
            <i class="nav-icon fas fa-th"></i>
            <p>
              Items
              <i class="fas fa-grip-lines right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'items:items_feed' %}" class="nav-link">
                <i class="far fa-dot-circle nav-icon"></i>
                <p>Items</p>
                <!-- <i class="fas fa-angle-left right"></i> -->
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'items:categories_feed'%}" class="nav-link">
                <i class="far fa-dot-circle nav-icon"></i>
                <p>Categories</p>
              </a>
            </li>
          </ul>
        </li>
        <li class="nav-item has-treeview menu-open">
          <a href="#" class="nav-link">
            <i class="nav-icon fa fa-box-open"></i>
            <p>
              Inventory
              <i class="fas fa-grip-lines right"></i>

            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'inventoryLoads:inventory_provider' %}" class="nav-link">
                <i class="far fa-dot-circle nav-icon"></i>
                <p>Providers</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'inventoryLoads:inventory_load_feed' %}" class="nav-link">
                <i class="far fa-dot-circle nav-icon"></i>
                <p>Loads</p>
              </a>
            </li>
          </ul>
        </li>
        <li class="nav-item has-treeview menu-open">
          <a href="#" class="nav-link">
            <i class="nav-icon far fa-file-alt"></i>
            <p>
              Orders
              <i class="fas fa-grip-lines right"></i>

            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="https://goyabaskets.herokuapp.com/" class="nav-link">
                <i class="far fa-dot-circle nav-icon"></i>
                <p>Ordes generated</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="https://goyabaskets.herokuapp.com/" class="nav-link">
                <i class="far fa-dot-circle nav-icon"></i>
                <p>Deliverys</p>
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>

templates/imagen.html
img{
width:50%;
position: absolute;
top:25%;
left: 25%;
}

img:hover{
transition: 0.5s;
transform: scale(1.5);
}


<div>
    <img src="https://image.flaticon.com/icons/svg/2041/2041103.svg" alt="">
</div>

templates/main.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title> GOYA | BCS </title>
  <link rel="icon" type="image/png" href="{% static '/img-dash/logo-item.png' %}" sizes="100x100">

  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static  '/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="{% static '/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static '/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static '/plugins/jqvmap/jqvmap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static '/css/adminlte.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static '/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static '/plugins/daterangepicker/daterangepicker.css' %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static '/plugins/summernote/summernote-bs4.css' %}">

  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body>
  <div class="wrapper">
    {% include 'navbar.html' %}
    {% include 'aside.html' %}
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-lg-2">
              {% block content_head %}
              {% endblock %}
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <section class="content-main">
        <div class="container-fluid">
          <!-- Small boxes (Stat box) -->
          <div class="row">
            {% block content_main %}
            {% endblock %}
          </div>
          <!-- /.row -->



        </div><!-- /.container-fluid -->
      </section>
      <!-- /.content -->
    </div>
    <footer class="main-footer">

      <strong>Copyright &copy; 2020 <a href="#"><span style="color: #E7811D "><a style="color: #E7811D; "
              href="https://www.batrescs.com/" target="_blank">Batres Creative Services</a></span></a></strong>
      <strong>All rights reserved. </strong>
      <div class="float-right d-none d-sm-inline-block">
        <b>V.</b> <span style="text-decoration: underline;">3.1.0.0</span>
      </div>
    </footer>
  </div>
</body>
<!-- jQuery -->
<script src="{% static  '/plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static  '/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static '/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static '/plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static '/plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{% static '/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static '/plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static '/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static '/plugins/moment/moment.min.js' %}"></script>
<script src="{% static '/plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static '/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static '/plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static '/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static '/js/adminlte.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static '/js/pages/dashboard.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static  '/js/demo.js' %}"></script>


</html>

templates/navbar.html
{% load static %}

<nav class="p-4 main-header navbar navbar-expand navbar-dark navbar-navy">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="index3.html" class="nav-link">Home</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="#" class="nav-link">Contact</a>
    </li>
  </ul>

  <!-- SEARCH FORM -->

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">

    <!-- Notifications Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">


        <div class="imagei d-flex" style="border-radius: 50% !important; padding-top: 2px !important; ">
          {% if request.user.profile.picture %}
          <img src="{{ request.user.profile.picture.url }}" class="img-circle elevation-2"
            style="max-width: 70px; margin-top: -25px !important;" alt="User Image" />

          {% else %}
          <img src="../static/media/profiles/userp.png" class="img-circle elevation-2"
            style="width: 70px; height: 70px; margin-top: -25px !important;" alt="">
          {% endif %}




          <div class="info ml-2 mt-1">
            <p class="text-user">{{ request.user.username}}</p>
          </div>
        </div>


      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <span class="dropdown-item dropdown-header">15 Notifications</span>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-envelope mr-2"></i> 4 new messages
          <span class="float-right text-muted text-sm">3 mins</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-users mr-2"></i> 8 friend requests
          <span class="float-right text-muted text-sm">12 hours</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-file mr-2"></i> 3 new reports
          <span class="float-right text-muted text-sm">2 days</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="{% url 'users:logout' %}" class="dropdown-item dropdown-footer">Logout</a>
      </div>
    </li>



  </ul>
</nav>

templates/paginator.html
<div class="pagination">
    <span class="step-links">

       {% if page_obj.has_previous %}
           <a href="?page=1">&laquo; first</a></li>
           <a href="?page={{ page_obj.previous_page_number }}">previous</a>
       {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

templates/searchbar.html
<style>

@font-face {
  font-family: goya-font;
  src: url(/static/fonts/GothamMedium.ttf);
}

/* body {
  background: #292826;
}

.wrapper {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
}*/


.container {
  padding: 3rem;
  width: 400px;
} 

input[type="search"] {
  -webkit-appearance: none !important;
  background-clip: padding-box;
  background-color: white;
  vertical-align: middle;
  border-radius: 0.25rem;
  border: 1px solid #e0e0e5;
  font-size: 1rem;
  font-family: goya-font;
  width: 100%;
  line-height: 2;
  padding: 0.375rem 1.25rem;
  -webkit-transition: border-color 0.2s;
  -moz-transition: border-color 0.2s;
  transition: border-color 0.2s;
}

input[type="search"]:focus {
  transition: all 0.5s;
  box-shadow: 0 0 20px #f9d442b9;
  border-color: #f9d342;
  outline: none;
  background-color: #212121;
  
}

form.search-form {
  display: flex;
  justify-content: center;
}

label {
  flex-grow: 1;
  flex-shrink: 0;
  flex-basis: auto;
  align-self: center;
  margin-bottom: 0;
}

input.search-field {
  margin-bottom: 0;
  flex-grow: 1;
  flex-shrink: 0;
  flex-basis: auto;
  align-self: center;
  height: 51px;
  border-top-right-radius: 0;
  border-bottom-right-radius: 0;
}

input.search-submit {
  height: 51px;
  margin: 0;
  padding: 1rem 1.3rem;
  border-top-left-radius: 0;
  border-bottom-left-radius: 0;
  border-top-right-radius: 0.25rem;
  border-bottom-right-radius: 0.25rem;
  font-family: "Font Awesome 5 Free";
  font-size: 1rem;
}

.screen-reader-text {
	
  clip: rect(1px, 1px, 1px, 1px);
  position: absolute !important;
  height: 1px;
  width: 1px;
  overflow: hidden;
}

.button {
  display: inline-block;
  font-weight: 600;
  font-size: 0.8rem;
  line-height: 1.15;
  letter-spacing: 0.1rem;
  text-transform: uppercase;
  background: #F4D44E;
  color: #292826;
  border: 1px solid transparent;
  vertical-align: middle;
  text-shadow: none;
  -webkit-transition: all 0.2s;
  -moz-transition: all 0.2s;
  transition: all 0.2s;
  
}

.button:hover,
.button:active,
.button:focus {
  cursor: pointer;
  background: #212121;
  color: #F4D44E;
  border-top-right-radius: 20px;
  border-bottom-right-radius: 20px;

  outline: 0;
}

</style>

<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Glowing Search Bar</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" type="text/css" media="screen" href="style.css" />

    <link
      href="https://fonts.googleapis.com/css2?family=Baloo+2&display=swap"
      rel="stylesheet"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"></script>
  </head>
<body>
  <div class="wrapper">
    <div class="container">
      <form role="search" method="get" class="search-form form" action="">
        <label>
            <span class="screen-reader-text">Search for...</span>
            <input type="search" class="search-field" placeholder="Type something..." value="" name="s" title="" />
        </label>
        <input type="submit" class="search-submit button" value="&#xf002" />
    </form>
    </div>
  </div>



    <script src="index.js"></script>
    
  </body>
</html>