Goya/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('items/', include(('items.urls', 'items'), namespace='items')),
    path('inventoryLoads/', include(('inventoryLoads.urls',
         'inventoryLoads'), namespace='inventoryLoads')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from dashboard import views

urlpatterns = [
    path(
        route='',
        view=views.welcome,
        name = 'welcome'
    ),
]

items/urls.py
from django.urls import path
from items import views

urlpatterns = [
    path(
        route='',
        view=views.ItemsListView.as_view(),
        name='items_feed'
    ),
    path(
        route='dashboard',
        view=views.items_dashboard,
        name='items_dashboard'
    ),
    path(
        route='new',
        view=views.item_new,
        name='item_new'
    ),
    path(
        route='item/<int:pk>',
        view=views.ItemEdit.as_view(),
        name='items_update'
    ),
    path(
        route='item/delete/<int:pk>',
        view=views.items_delete,
        name='items_delete'
    ),
    path(
        route='categories/',
        view=views.categories_feed,
        name='categories_feed'
    ),
    path(
        route='categories/<int:pk>',
        view=views.CategoryEdit.as_view(),
        name='categories_edit'
    ),
    path(
        route='categories/new',
        view=views.CategoryCreate.as_view(),
        name='categories_new'
    ),
    path(
        route='categories/delete/<int:pk>',
        view=views.categories_delete,
        name='categories_delete'
    ),
]

dashboard/models.py
from django.db import models

# Create your models here.

items/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=80)
    description = models.TextField(max_length=500, null=True)
    last_user_update = models.ForeignKey(User, on_delete=models.PROTECT)
    last_date_update = models.DateField(auto_now=True)

    def __str__(self):
        return self.name


class Item(models.Model):
    name = models.CharField(max_length=200, unique=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(max_length=500, null=True)
    stock = models.PositiveIntegerField()
    category = models.ForeignKey(
        Category, null=False, on_delete=models.PROTECT)
    last_user_update = models.ForeignKey(User, on_delete=models.PROTECT)
    last_date_update = models.DateField(auto_now=True)
    photo = models.ImageField(
        upload_to='items/', default='items/default.png')

    def __str__(self):
        return self.name

items/forms.py
from django import forms
from items.models import Item, Category

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'


class CategoryForm(forms.Form):
    model = Category
    fields = ('name', 'description')

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required
def welcome(request):

    context = {}

    return render(request, 'welcome.html', context)

items/views.py
from django.shortcuts import render, redirect
from items.models import Item, Category
from items.forms import *
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

# Create your views here.o


class ItemsListView(LoginRequiredMixin, ListView):
    template_name = 'items/feed.html'
    model = Item
    paginate_by = 10
    context_object_name = 'items'


@login_required
def item_new(request):
    item_form = ItemForm()
    if request.method == 'POST':
        item_form = ItemForm(request.POST, request.FILES)
        if item_form.is_valid():
            item_form.save()
            return redirect('items:items_feed')
    context = {
        'form': item_form,
    }
    return render(request, 'items/new_item.html', context)


class ItemEdit(LoginRequiredMixin, UpdateView):
    model = Item
    fields = '__all__'
    template_name = 'items/edit_item.html'
    success_url = reverse_lazy('items:items_feed')


class CategoryEdit(LoginRequiredMixin, UpdateView):
    model = Category
    fields = '__all__'
    template_name = 'items/category_edit.html'
    success_url = reverse_lazy('items:categories_feed')


@login_required
def items_delete(request, pk):
    item = Item.objects.get(id=pk)
    item.delete()
    context = {
        'item': item
    }
    return redirect('items:items_feed')


@login_required
def categories_feed(request):
    categories = Category.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'items/categories_feed.html', context)


@login_required
def categories_delete(request, pk):
    categories = Category.objects.get(id=pk)
    categories.delete()
    context = {
        'categories': categories
    }
    return redirect('items:categories_feed')


class CategoryCreate(LoginRequiredMixin, CreateView):
    template_name = 'items/category_new.html'
    model = Category
    fields = '__all__'
    success_url = reverse_lazy('items:categories_feed')


@login_required
def items_dashboard(request):
    items = Item.objects.all()
    categories = Category.objects.all()
    tags_coutn = Tag.objects.all().annotate(item_count=models.Count('item'))
    context = {
        'items': items[:10],
        'categiries': categories[:10],
        'tags': tags_coutn
    }
    return render(request, 'items/dashboard.html', context)


# @login_required
# def item_delete(request)
#item = ItemDelete.objects.get(id=id)
# item.delete()
# return render(request, 'items/new_item.html', context)

templates/items/categories_feed.html
{% extends 'main.html' %}


<!-- <h1 class="m-0 text-dark">Dashboard</h1> -->block %}
{% block content_main %}
{%include 'searchbar.html'%}

<!-- <div class = "col-md-1 pl-5" style="align-items: flex-end;">
        <a  href="{% url 'items:item_new' %}" class = "btn-add-item " id="rotation"> </a>
    </div> -->
<br>

<div class="col-12 pl-5 pr-5">
  <div class="card">
    <div class="card-header bk-tab">
      <h3 class="card-title text-goya ">CATEGORIES</h3>

      <div class="col-md-1 pl-5" style="align-items: flex-end;">
        <a href="{% url 'items:categories_new' %}" class="btn-add-item " id="rotation"> </a>
      </div>
      <div class="card-tools">

      </div>
    </div>
  </div>

  <!-- /.card-header -->
  <div class="card-body table-responsive p-0">
    <table class="table table-hover text-nowrap">
      <thead class="head-td">
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Options</th>
        </tr>
      </thead>
      <tbody>
        {% for category in categories %}

        <td>{{ category.name }}</td>
        <td style="text-align: left !important;">{{ category.description }}</td>
        <td>
          <div class="btn-group">
            <a href="{% url 'items:categories_edit' category.pk %}" class="btn btn-info">Edit</a>
            <a href="{% url 'items:categories_delete' category.pk %}"" class=" btn btn-danger">Delete</a>
          </div>
        </td>
        </tr>
        {% endfor %}

      </tbody>

    </table>
  </div>
  <!-- /.card-body -->
</div>
<!-- /.card -->
</div>
<div style="margin-top: 20px; height: 150px;" class="pl-5">
  <div class="pagination pl-5">


  </div>
  {% include 'paginator.html' %}
</div>




{% endblock %}

templates/items/category_edit.html
{% extends 'main.html' %}
{% block content_head %}

{% endblock %}
{% block content_main %}

<div class="col-10 form-item">
            <div class="card card-secondary d-flex justify-content-center form-item">
              <div class="card-header justify-content-center">
                <h3 class="card-title justify-content-center">EDIT CATEGORYE</h3>
                <div>
        <a class = "btn btn-danger text-align-left" href = "{% url 'items:items_feed'%}"> Back</a>
      </div>
              </div>
                <div class="card-body">
                 <form method="POST" enctype="multipart/form-data" >
                    {% csrf_token %}
                    {# Website field #}
                    <div class="col-sm-6 form-item">
                      <div class="form-group" style="font-family: goya-font;">
                        <label>Name</label>
                        <input
                            class="form-control {% if form.name.errors %}is-invalid{% endif %}"
                            type="text"
                            name="name"
                            id = "name"
                            value = {{ form.name.value }}
                            placeholder="Insert the category name ..."
                        >
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}{{ error }}{% endfor %}
                        </div>
                        </div>
                      <div class="form-group" style="font-family: goya-font;">
                        <label>Description</label>
                        <textarea class="form-control" rows="3" placeholder="Enter the description..." id="description" name="description">
                        {{ form.description.value }}
                        </textarea>
                      </div>
                    </div>
                    {# Photo field #}
                 
                    <input type="hidden" id = "last_user_update" name = "last_user_update" value = "{{user.pk}}" />

                    <button type="submit" class="btn btn-primary-item btn-block mt-5">Add!</button>
                </form>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>

{% endblock %}

templates/items/category_new.html
{% extends 'main.html' %}
{% block content_head %}

{% endblock %}
{% block content_main %}

<div class="col-10 form-item">
            <div class="card card-secondary d-flex justify-content-center form-item">
              <div class="card-header justify-content-center">
                <h3 class="card-title justify-content-center">NEW CATEGORYE</h3>
                <br>
                <div>
        <a class = "btn btn-danger text-align-left" href = "{% url 'items:items_feed'%}"> Back</a>
      </div>
              </div>
                <div class="card-body">
                 <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {# Website field #}
                    <div class="col-sm-6 form-item">
                      <div class="form-group" style="font-family: goya-font;">
                        <label>Name</label>
                        <input
                            class="form-control {% if form.name.errors %}is-invalid{% endif %}"
                            type="text"
                            name="name"
                            id = "name"
                            placeholder="Insert the category name ..."
                        >
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}{{ error }}{% endfor %}
                        </div>
                        </div>
                      <div class="form-group" style="font-family: goya-font;">
                        <label>Description</label>
                        <textarea class="form-control" rows="3" placeholder="Enter the description..." id="description" name="description"></textarea>
                      </div>
                    </div>
                    {# Photo field #}
                 
                    <input type="hidden" id = "last_user_update" name = "last_user_update" value = "{{user.pk}}" />

                    <button type="submit" class="btn btn-primary-item btn-block mt-5">Add!</button>
                </form>

              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>

{% endblock %}

templates/items/dashboard.html
{% extends 'main.html' %}
{% block content_head %}
<h1 class="m-0 text-dark">Dashboard</h1>
{% endblock %}
{% block content_main %}
<div class="col-lg-7">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Recently Added Products</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove">
                    <i class="fas fa-times"></i>
                </button>
            </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body p-0">
            <ul class="products-list product-list-in-card pl-2 pr-2">
                {% for item in items %}
                <li class="item">
                    <div class="product-img">
                        <img src="{{ item.photo }}" alt="{{ item.name }}" class="img-size-100">
                    </div>
                    <div class="product-info">
                        <a href="javascript:void(0)" class="product-title">{{ item.name }}
                            <span class="badge badge-warning float-right">{{ item.price }}</span></a>
                        <span class="product-description">
                            {{ item.description }}
                        </span>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
        <!-- /.card-body -->
        <div class="card-footer text-center">
            <a href="{% url 'items:items_feed' %}" class="uppercase">View All Products</a>
        </div>
        <!-- /.card-footer -->
    </div>
</div>
<div class="col-lg-4">

    <div class="card">
        <div class="card-header border-0">
            <h3 class="card-title">Categories</h3>
            <div class="card-tools">
                <a href="#" class="btn btn-tool btn-sm">
                    <i class="fas fa-download"></i>
                </a>
                <a href="#" class="btn btn-tool btn-sm">
                    <i class="fas fa-bars"></i>
                </a>
            </div>
        </div>
        <div class="card-body table-responsive p-0">
            <table class="table table-striped table-valign-middle">
                <thead>
                    <tr>
                        <th>Category</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    {% for categiry in categiries %}
                    <tr>
                        <td>{{ categiry.name }}</td>
                        <td>{{ categiry.description }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="card-footer text-center">
            <a href="{% url 'items:categories_feed' %}" class="uppercase">View All Categoriees</a>
        </div>
    </div>
</div>

{% endblock %}

templates/items/edit_item.html
{% extends 'main.html' %}
{%  load static %}
{% load widget_tweaks %}
{% block content_head %}

{% endblock %}
{% block content_main %}
<div class="col-10 form-item">

  <div class="card card-secondary d-flex justify-content-center form-item">
    <div class="card-header justify-content-center">
      <h3 class="card-title justify-content-center" style="font-family: goya-font;">Edit Items</h3>
      <div>
        <a class = "btn btn-danger text-align-left" href = "{% url 'items:items_feed'%}"> Back</a>
      </div>
    </div>
    <div class="card-body">

      <form method="post" enctype="multipart/form-data" >
        {% csrf_token %}

        <div class="col-sm-6 form-item">
          <!-- text input -->
          <div class="form-group" style="font-family: goya-font;">
            <label>Name</label>
            <input 
            type="text" 
            class="form-control" 
            placeholder="Enter the item name ..." 
            name="name" 
            id = "name" 
            value="{{ form.name.value}}">
            
              {% for error in form.name.errors %}
                  {{ error }}
              {% endfor %}
          </div>

          <div class="form-group" style="font-family: goya-font;">
            <label>Price</label>
            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text">$</span>
              </div>
              <input 
                type="text" 
                class="form-control" 
                placeholder="Price" 
                name="price"
                id="price"
                value = "{{ form.price.value }}">
                
                {% for error in form.price.errors %}
                  {{ error }}
                {% endfor %}
            </div>
          </div>
          <div class="form-group" style="font-family: goya-font;">
            <label>Description</label>
            <textarea 
              class="form-control" 
              rows="3" 
              placeholder="Enter the description..." 
              name="description"
              >{{ form.description.value }}
              </textarea>
            {% for error in form.description.errors %}
              {{ error }}
            {% endfor %}
          </div>
          <div class="form-group" style="font-family: goya-font;">
            <label>Stock</label>
            <input 
              type="text" 
              class="form-control" 
              placeholder="Enter the stock ..." 
              name="stock" 
              id = "stock" 
              value = "{{form.stock.value}}">
               {% for error in form.stock.errors %}
                            {{ error }}
                        {% endfor %}

          </div>
          <div class="form-group" style="font-family: goya-font;">
          <label>Category</label>
            <select 
              name="{{ form.category.name }}" 
              value = "{{form.category.value}}" 
              class = "form-control" >
                {% for choice in form.category.field.choices %}
                    <option value="{{ choice.0 }}"    
                    {% if choice.0 == form.category.value%}
                      selected
                      {% endif %}
                    
                    >{{ choice.1 }}</option>
                {% endfor %}
            </select>
              {% for error in form.category.errors %}
                {{ error }}
              {% endfor %}

          </div>
          
          <input type="hidden" id = "last_user_update" name = "last_user_update" value = "{{user.pk}}" />
          
        </div>
        <button class="btn btn-primary-item btn-block mt-5" type="submit">
          Update
        </button>
      </form>

    </div>
    <!-- /.card-body -->
  </div>

</div>

{% endblock %}

templates/items/feed.html
{% extends 'main.html' %}


<!-- <h1 class="m-0 text-dark">Dashboard</h1> -->block %}
{% block content_main %}
{%include 'searchbar.html'%}

<!-- <div class = "col-md-1 pl-5" style="align-items: flex-end;">
        <a  href="{% url 'items:item_new' %}" class = "btn-add-item " id="rotation"> </a>
    </div> -->
<br>
<style>
  .zoomimg {
    width: 10%;
    position: relative;
    top: 0%;
    left: 0%;
  }

  .zoomimg:hover {

    padding: 20px;
    width: 40%;
    background-color: #fefefe;
    transition: 0.2s;
    transform: scale(2.5);
  }
</style>
<div class="col-12 pl-5 pr-5">
  <div class="card">
    <div class="card-header bk-tab">
      <h3 class="card-title text-goya ">ITEMS</h3>

      <div class="col-md-1 pl-5" style="align-items: flex-end;">
        <a href="{% url 'items:item_new' %}" class="btn-add-item " id="rotation"> </a>
      </div>
      <div class="card-tools">

      </div>
    </div>
  </div>

  <!-- /.card-header -->
  <div class="card-body table-responsive p-0">
    <table class="table table-hover text-nowrap">
      <thead class="head-td">
        <tr>
          <th>Image</th>
          <th>Name</th>
          <th>Price</th>
          <th>Description</th>
          <th>Stock</th>
          <th>Category</th>
          <th>Options</th>
        </tr>
      </thead>
      <tbody>
        {% for item in items %}
        <td>
          <div class="zoomimg">
            <img src="{{ item.photo.url }}" alt="" width="80px" style="margin-left: auto; margin-right: auto;">
          </div>
        </td>
        <td>{{ item.name }}</td>
        <td>{{ item.price }}</td>
        <td style="text-align: left !important;">{{ item.description }}</td>
        <td>
          {% if item.stock > 0 %}
          <span class="tag tag-success">{{ item.stock }} aviable</span>
        </td>
        {% else %}
        <span class="tag tag-danger">{{ item.stock }} whitout products</span>
        {% endif %}
        <td>{{ item.category.name }}</td>
        <td>
          <div class="btn-group">
            <a href="{% url 'items:items_update' item.id %}" class="btn btn-info">Edit</a>
            <a href="{% url 'items:items_delete' item.id %}" class="btn btn-danger">Delete</a>
          </div>
        </td>
        </tr>
        {% endfor %}

      </tbody>

    </table>
  </div>
  <!-- /.card-body -->
</div>
<!-- /.card -->
</div>
<div style="margin-top: 20px; height: 150px;" class="pl-5">
  <div class="pagination pl-5">


  </div>
  {% include 'paginator.html' %}
</div>




{% endblock %}

templates/items/list.html
{% extends 'main.html' %}
{% block content %}
<div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">DataTable with minimal features &amp; hover style</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4"><div class="row"><div class="col-sm-12 col-md-6"></div><div class="col-sm-12 col-md-6"></div></div><div class="row"><div class="col-sm-12"><table id="example2" class="table table-bordered table-hover dataTable dtr-inline" role="grid" aria-describedby="example2_info">
                  <thead>
                  <tr role="row">
                      <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">Producto</th>
                      <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Descripcion</th>
                      <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Stock<th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Engine version</th><th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">CSS grade</th></tr>
                  </thead>
                  <tbody>
                      {% for articulo in articulos %}
                  <tr role="row" class="odd">
                      <td tabindex="0" class="sorting_1">{{articulo.name}}</td>
                      <td>{{articulo.price}}</td>
                      <td>{{articulo.description}}</td>
                      <td>{{articulo.stock}}</td>
                      <td>{{articulo.category.name}}</td>
                      <td>{{articulo.photo.url}}</td>
                  </tr>
                  {% endfor %} 

                  </tbody>
                  <tfoot>
                  <tr><th rowspan="1" colspan="1">Rendering engine</th><th rowspan="1" colspan="1">Browser</th><th rowspan="1" colspan="1">Platform(s)</th><th rowspan="1" colspan="1">Engine version</th><th rowspan="1" colspan="1">CSS grade</th></tr>
                  </tfoot>
                </table></div></div><div class="row"><div class="col-sm-12 col-md-5"><div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div></div><div class="col-sm-12 col-md-7"><div class="dataTables_paginate paging_simple_numbers" id="example2_paginate"><ul class="pagination"><li class="paginate_button page-item previous disabled" id="example2_previous"><a href="#" aria-controls="example2" data-dt-idx="0" tabindex="0" class="page-link">Previous</a></li><li class="paginate_button page-item active"><a href="#" aria-controls="example2" data-dt-idx="1" tabindex="0" class="page-link">1</a></li><li class="paginate_button page-item "><a href="#" aria-controls="example2" data-dt-idx="2" tabindex="0" class="page-link">2</a></li><li class="paginate_button page-item "><a href="#" aria-controls="example2" data-dt-idx="3" tabindex="0" class="page-link">3</a></li><li class="paginate_button page-item "><a href="#" aria-controls="example2" data-dt-idx="4" tabindex="0" class="page-link">4</a></li><li class="paginate_button page-item "><a href="#" aria-controls="example2" data-dt-idx="5" tabindex="0" class="page-link">5</a></li><li class="paginate_button page-item "><a href="#" aria-controls="example2" data-dt-idx="6" tabindex="0" class="page-link">6</a></li><li class="paginate_button page-item next" id="example2_next"><a href="#" aria-controls="example2" data-dt-idx="7" tabindex="0" class="page-link">Next</a></li></ul></div></div></div></div>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>

{% endblock %}

templates/items/new_item.html
{% extends 'main.html' %}
{%  load static %}
{% load widget_tweaks %}
{% block content_head %}

{% endblock %}
{% block content_main %}
<div class="col-10 form-item">

  <div class="card card-secondary d-flex justify-content-center form-item">
    <div class="card-header justify-content-center">
      <h3 class="card-title-add justify-content-center" style="font-family: goya-font;;">+ ITEM FORMS</h3>
      <div>
      
        <a class = "btn btn-danger text-align-left" href = "{% url 'items:items_feed'%}"> Back</a>
      </div>
    </div>
    <div class="card-body">

      <form  method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="col-sm-6 form-item">
          <!-- text input -->
          <div class="form-group" style="font-family: goya-font;">
            <label>Name</label>
            <input type="text" class="form-control" placeholder="Enter the item name ..." name="name" id = "name">
               {% for error in form.name.errors %}
                            {{ error }}
                        {% endfor %}

          </div>

          <div class="form-group" style="font-family: goya-font;">
            <label>Price</label>
            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text">$</span>
              </div>
              <input type="text" class="form-control" placeholder="Price" name="price">
                  {% for error in form.price.errors %}
                            {{ error }}
                        {% endfor %}

            </div>
          </div>
          <div class="form-group" style="font-family: goya-font;">
            <label>Description</label>
            <textarea class="form-control" rows="3" placeholder="Enter the description..." name="description"></textarea>
               {% for error in form.description.errors %}
                            {{ error }}
                        {% endfor %}

          </div>
          <div class="form-group" style="font-family: goya-font;">
            <label>Stock</label>
            <input type="text" class="form-control" placeholder="Enter the stock ..." name="stock" id = "stock">
               {% for error in form.stock.errors %}
                            {{ error }}
                        {% endfor %}

          </div>

          <div class="form-group" style="font-family: goya-font;">
            <label>imagen</label>
  <input type="file" id="photo" name="photo" accept="image/*">
                           {% for error in form.stock.errors %}

                            {{ error }}
                        {% endfor %}
            </div>
          <div class="form-group" style="font-family: goya-font;">
          <label>Category</label>
            <select name="{{ form.category.name }}" class = "form-control">
                {% for choice in form.category.field.choices %}
                    <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                {% endfor %}
            </select>
               {% for error in form.category.errors %}
                            {{ error }}
                        {% endfor %}

              
          </div>
          <input type="hidden" id = "last_user_update" name = "last_user_update" value = "{{user.pk}}" />
        </div>
        <button class="btn btn-primary-item btn-block mt-5" type="submit">Register!</button>
      </form>

    </div>
    <!-- /.card-body -->
  </div>

</div>

{% endblock %}